### ISSUE TITLE
Multiple menus when dragging and dropping

### ISSUE THREAD

**Issue by sierra-acy-zz** [RoyFalik/bitwise#1]
When you drag a number onto another number, it creates a menu of XOR, AND, etc. If you drag the same number onto the same number again, it adds the same menu to the previous menu (so there are 2 sets of XOR, AND, etc.).

**Comment by RoyFalik** [comment]
The bigger issue is that when you drop something onto the "action" button of something else, then the element comparison occurs between the dropped one and the button as opposed to the dropped one and the one it was dropped onto. Same issue- gonna try to work on fixing it.
